config/routes.rb
require "resque_web"

Rails.application.routes.draw do
    mount ResqueWeb::Engine => "/resque_web"

    #devise_for :users

    namespace :backend do
        resources :subscriptions, except: [:show]
        get 'comments', to: 'comments#index'
        resources :blogs, except: [:show] do
            resources :comments, except: [:create, :new, :show, :index]
        end
    end

    put 'recreate_images', to: 'backend/blogs#change_size'

    post '/:blog_id/comments', to: 'frontend/comments#create', as: 'new_comment'

    root to: "frontend/blogs#index"
    get '/subscribe', to: 'frontend/subscriptions#new'
    post '/subscribe', to: 'frontend/subscriptions#create'
    post '/:id/create_comment', to: 'frontend/comments#create', as: 'createcomment'
    get '/:id', to: 'frontend/blogs#show', as: 'blog'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :title, length: { minimum: 5 }

    mount_uploader :image, ImageUploader


    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]

    scope :published_posts, -> {where(active: true)}

    self.per_page = 4

    after_commit :enqueue_counterworker, on: [:create, :update]
    after_commit :emailsworker, on: [:create, :update]

    def self.send_subscription_emails
        UserMailer.welcome_email.deliver
    end

    private

    def enqueue_counterworker
        Resque.enqueue(Counter, id)
    end

    def emailsworker
        if active && !notified
            Resque.enqueue(NotifySubscribers, id)
            update(notified: true)
        end
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :blog

    validates :body, presence: true
    validates :body, length: { minimum: 5 }
    validates :commenter, presence: true
    validates :body, format: { with: /\A[a-zA-Z]+\z/, message: 'Only Letters are allowed!'}
    validates :body, presence: true

    extend FriendlyId
    friendly_id :comment_slug, use: [:slugged, :finders]

    scope :active, -> {where(active: true)}

    def comment_slug
        "#{commenter} #{created_at.to_i}"
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    validates :email, presence: true

    def name
        "#{first_name} #{last_name}"
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/backend/blogs_controller.rb
module Backend
    class BlogsController < ApplicationController
        before_action :find_blog, only: [:show, :edit, :update, :destroy, :active]

        def index
            @blogs = Blog.all.paginate(page: params[:page])
        end

        def create
            @blog = Blog.new(blog_params)
            if @blog.save
                redirect_to backend_blogs_path, notice: "Success!"
            else
                render "new"
            end
        end

        def edit
        end

        def new
            @blog = Blog.new
        end

        def update
            if @blog.update(blog_params)
              redirect_to backend_blogs_path
            else
              render 'edit'
            end
        end

        def destroy
            @blog.destroy
            flash[:notice] = "Delete success"
            redirect_to backend_blogs_path
        end

        def change_size
            Resque.enqueue(ImagesWorker)
            redirect_to backend_blogs_path, notice: "worker enqueued"
        end

        private

        def find_blog
            @blog = Blog.find(params[:id])
        end

        def blog_params
            params.require(:blog).permit(:title, :text, :image, :image_cache, :active, :notified, :wordcount, :whitespacecount, :charactercount)
        end
    end
end

app/controllers/backend/comments_controller.rb
module Backend
    class CommentsController < ApplicationController
        before_action :find_blog, except: [:index]
        before_action :find_comment, except: [:index]


        def index
            @comments = Comment.all.paginate(page: params[:page])
        end

        def edit
        end

        def update
            if @comment.update(comment_params)
                redirect_to backend_blog_path(@blog)
            else
                render 'edit'
            end
        end

        def destroy
            @comment.destroy
            redirect_to backend_blog_path(@blog, notice: "Delete success")
        end

        private

        def find_blog
            @blog = Blog.find(params[:blog_id])
        end

        def find_comment
            @comment = @blog.comments.find(params[:id])
        end

        def comment_params
            params.require(:comment).permit(:commenter, :title, :body, :blog_id, :id)
        end
    end
end

app/controllers/backend/subscriptions_controller.rb
module Backend
    class SubscriptionsController < ApplicationController
        before_action :find_subscription
        def create
            @subscription = Subscription.new(subscription_params)
            if @subscription.save
                redirect_to root_path, alert: "Thanks for subscribing"
            else
                render "new"
            end
        end

        def new
            @subscription = Subscription.new
        end


        private

        def subscription_params
            params.require(:subscription).permit(:first_name, :last_name, :email)
        end
    end
end




before_action :find_blog, only: [:show, :edit, :update, :destroy, :active]

def index
    @blogs = Blog.all.paginate(page: params[:page])
end

def create
    @blog = Blog.new(blog_params)
    if @blog.save
        redirect_to backend_blogs_path, notice: "Success!"
    else
        render "new"
    end
end

def edit
end

def new
    @blog = Blog.new
end

def update
    if @blog.update(blog_params)
      redirect_to backend_blogs_path
    else
      render 'edit'
    end
end

def destroy
    @blog.destroy
    flash[:notice] = "Delete success"
    redirect_to backend_blogs_path
end

app/controllers/frontend/blogs_controller.rb
module Frontend
    class BlogsController < ApplicationController
        protect_from_forgery

        def index
            @blogs = Blog.published_posts.paginate(page: params[:page])
        end

        def show
           @blog = Blog.find(params[:id])
           @comment = @blog.comments.new
        end
    end
end

app/controllers/frontend/comments_controller.rb
module Frontend
    class CommentsController < ApplicationController
        protect_from_forgery

        def create
            @blog = Blog.find(params[:blog_id])
            @comment = @blog.comments.new(comment_params)
            if @comment.save
                redirect_to blog_path(@blog)
            else
                redirect_to blog_path(@blog), alert: "This did not save"
            end
        end

        private

        def comment_params
            params.require(:comment).permit(:commenter, :title, :body, :blog_id, :id)
        end
    end
end

app/controllers/frontend/subscriptions_controller.rb
module Frontend
    class SubscriptionsController < ApplicationController
        def create
            @subscription = Subscription.new(subscription_params)
            if @subscription.save
                redirect_to root_path, alert: "Thanks for subscribing"
            else
                render "new"
            end
        end

        def new
            @subscription = Subscription.new
        end


        private

        def subscription_params
            params.require(:subscription).permit(:first_name, :last_name, :email)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/backend/blogs/_form.html.erb
<%= form_for [:backend, @blog], html: { class: 'form-horizontal'} do |form| %>

    <% if @blog.errors.any? %>
       <div id="error_explanation">
            <h2>
                <%= pluralize(@blog.errors.count, "error") %> prohibited
                   this blog from being saved:
            </h2>
            <ul>
                <% @blog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :active %><br>
        <%= form.check_box :active, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :notified %><br>
        <%= form.check_box :notified, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :text %><br>
        <%= form.text_area :text, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :image %><br>
        <%= form.file_field :image, class: 'form-control' %>
        <%= form.hidden_field :image_cache %>
        <%= image_tag(@blog.image_url(:medium), alt: 'Image') if @blog.image? %>
    </div>

    <p>
        <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
    </p>

<% end %>

app/views/backend/blogs/edit.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts' %></li>
    <li><%= link_to @blog.title, backend_blog_path(@blog) %></li>
    <li class="active">Edit</li>
</ol>

<%= render 'form' %>

app/views/backend/blogs/index.html.erb
<ol class="breadcrumb">
    <li class="active">Blogposts</li>
</ol>

<div class="welcome-image text-center">
    <img src="<%= asset_path( 'welcome_burned.png' ) %>" />
</div>

<%= link_to 'recreate images', recreate_images_path, method: :put %>

<div class="table-responsive">
    <table class="table table-hover text-center">
        <thead>
            <tr>
                <th class="text-center">Published</th>
                <th class="text-center">Title</th>
                <th class="text-center">Text</th>
                <th class="text-center">Picture</th>
                <th class="text-center">WordCount</th>
                <th class="text-center">WhitespaceCount</th>
                <th class="text-center">CharacterCount</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>

        <% @blogs.each do |blog| %>
            <tr>
                <td class="text-center"><%= blog.active %></td>
                <td class="text-center"><%= blog.title %></td>
                <td class="text-center"><%= blog.text %></td>
                <td class="text-center"><%= image_tag(blog.image_url(:medium), alt: 'Image') if blog.image? %></td>
                <td class="text-center"><%= blog.wordcount %></td>
                <td class="text-center"><%= blog.whitespacecount %></td>
                <td class="text-center"><%= blog.charactercount %></td>
               <td><%= link_to 'Edit', edit_backend_blog_path(blog), class: 'btn btn-info' %>
               <%= link_to 'Delete', backend_blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
    </table>


<div class="row">
    <div class="col-md-12 text-center">
        <div class="new-blog">
        <%= link_to 'New Blog', new_backend_blog_path, class: 'btn btn-success' %>
        </div>
    </div>
</div>

<%= will_paginate @blogs %>

app/views/backend/blogs/new.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts'%></li>
    <li class="active">New</li>
</ol>

<%= render 'form' %>

app/views/backend/blogs/show.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts', backend_blogs_path %></li>
    <li class="active"><%= @blog.title %></li>
</ol>

<div class="row">
    <div class="col-md-12">
        <div class="calm-welcome text-center">
                <img src="<%= asset_path( 'calm-welcome.png' ) %>" />
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body text-center"><%= image_tag(@blog.image_url(:medium), alt: 'Image') if @blog.image? %>
                <h4>Your Story</h4>
            </div>
        </div>
        <div class="main-text-box">
             <p><%= @blog.text %></p>
        </div>
    </div>
</div>

<div class="col-md-12 text-center">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="text-center">Commenter</th>
                    <th class="text-center">Comment</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>

            <% @blog.comments.each do |comment| %>

            <tbody>
                <tr>
                    <td><%=comment.commenter %></td>
                    <td><%=comment.body %></td>
                </tr>
            </tbody>

            <% end %>
        </table>
    </div>
</div>
    <%= link_to 'Edit', edit_backend_blog_path(@blog) %>
    <%= link_to 'Back', backend_blogs_path %>
</div>

app/views/backend/comments/edit.html.erb
<div class="row">
    <div class="col-md-12 text-center">
       <%= form_for [:backend, @blog, @comment] do |form| %>
            <div class="form-group text-center">
                <p>
                    <%= form.label :commenter %><br>
                    <%= form.text_field :commenter %>
                </p>
                <p>
                    <%= form.label :body %><br>
                    <%= form.text_area :body %>
                </p>
                <p>
                    <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
                </p>
            </div>
        <% end %>
    </div>
</div>

app/views/backend/comments/index.html.erb
<div class="panel panel-success">
     <div class="panel-heading text-center">Backend Comments Index</div>
     <div class="panel-body">
         <div class="table-responsive">
             <table class="table table-hover text-center">
                 <thead>
                     <tr>
                         <th>Commenter</th>
                         <th>Comment</th>
                         <th>Actions</th>
                     </tr>
                 </thead>
                 <% @comments.each do |comment| %>
                     <tr>
                         <td><%= comment.commenter %></td>
                         <td><%= comment.body.truncate(10) %></td>
                         <td>
                             <%= link_to 'Edit', edit_backend_blog_comment_path(comment.blog, comment), class: 'btn btn-primary' %>
                             <%= link_to 'Delete', backend_blog_comment_path(comment.blog, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                         </td>

                     </tr>
                 <% end %>
             </table>
         </div>
     </div>
</div>


<ol class="breadcrumb">
    <li class="active">Comments</li>
</ol>


<%= will_paginate @comments %>

app/views/blogs/backend/_form.html.erb
<%= form_for :blog, url: blogs_path, html: { class: 'form-horizontal'} do |form| %>

    <% if @blog.errors.any? %>
       <div id="error_explanation">
            <h2>
                <%= pluralize(@blog.errors.count, "error") %> prohibited
                   this blog from being saved:
            </h2>
            <ul>
                <% @blog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>



    <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :text %><br>
        <%= form.text_area :text, class: 'form-control' %>
    </div>


    <div class="form-group">
        <%= form.label :image %><br>
        <%= form.file_field :image, class: 'form-control' %>
        <%= form.hidden_field :image_cache %>
        <%= image_tag(@blog.image_url(:thumb), alt: 'Image') if @blog.image? %>
    </div>

    <p>
        <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
    </p>

<% end %>

app/views/blogs/backend/index.html.erb
<ol class="breadcrumb">
    <li class="active">Blogposts</li>
</ol>

<div class="welcome-image text-center">
    <img src="<%= asset_path( 'welcome_burned.png' ) %>" />
</div>

<div class="table-responsive">
    <table class="table table-hover text-center">
        <thead>
            <tr>
                <th>Title</th>
                <th>Text</th>
                <th>Picture</th>
                <th>Actions</th>
            </tr>
        </thead>
        <% @blogs.each do |blog| %>
            <tr>
                <td><%= blog.title %></td>
                <td><%= blog.text %></td>
                <td><%= image_tag(blog.image_url(:thumb), alt: 'Image') if blog.image? %></td>
                <td><%= link_to 'Show', blog_path(blog) %>
                <%= link_to 'Edit', edit_blog_path(blog) %>
                <%= link_to 'Delete', blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </table>


    <div class="linktonewblog">
        <%= link_to 'New Blog', new_blog_path, class: 'btn btn-success' %>
    </div>

</div>

<%= will_paginate @blogs %>

app/views/blogs/backend/new.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts'%></li>
    <li class="active">New</li>
</ol>

<%= render 'blogs/backend/form' %>

app/views/blogs/edit.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts' %></li>
    <li><%= link_to @blog.title, blog_path(@blog) %></li>
    <li class="active">Edit</li>
</ol>

<%= render 'form' %>

app/views/blogs/show.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Blogposts' %></li>
    <li class="active"><%= @blog.title %></li>
</ol>

<div class="row">
    <div class="col-md-12">
        <div class="calm-welcome text-center">
                <img src="<%= asset_path( 'calm-welcome.png' ) %>" />
        </div>
    </div>
</div>


<div class="row">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Text</th>
                    <th>Image</th>

                </tr>
            </thead>
                <tr>
                    <td><%= @blog.title %></td>
                    <td><%= @blog.text %></td>
                    <td><%= image_tag(@blog.image_url(:thumb), alt: 'Image') if @blog.image? %></td>
                </tr>
        </table>

    <div class="col-md-12 text-center">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th class="text-center">Commenter</th>
                        <th class="text-center">Comment</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>

                <% @blog.comments.each do |comment| %>

                <tbody>
                    <tr>
                        <td><%=comment.commenter %></td>
                        <td><%=comment.body %></td>
                        <td><%= link_to 'Destroy', [comment.blog, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                </tbody>

                <% end %>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 text-center">
       <%= form_for [@blog, @comment] do |form| %>
            <div class="form-group text-center">
                <p>
                    <%= form.label :commenter %><br>
                    <%= form.text_field :commenter %>
                </p>
                <p>
                    <%= form.label :body %><br>
                    <%= form.text_area :body %>
                </p>
                <p>
                    <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
                </p>
            </div>
        <% end %>
    </div>
    <%= link_to 'Edit', edit_blog_path(@blog) %>
    <%= link_to 'Back', blogs_path %>
</div>

app/views/frontend/blogs/index.html.erb
<div class="welcome-image text-center">
    <img src="<%= asset_path( 'welcome_burned.png' ) %>" />
</div>

<div class="row">
    <% @blogs.each do |blog| %>
        <div class='col-lg-4 col-md-6'>
            <div class="image">
                <h4><%= link_to blog.title, blog_url(blog) %></h4>
                <%= image_tag(blog.image_url(:medium), class: "img-responsive") %>
            </div>
        </div>
    <% end %>
</div>

<%= will_paginate @blogs %>

app/views/frontend/blogs/show.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'Home', root_url %></li>
    <li class="active"><%= @blog.title %></li>
</ol>

<div class="row">
    <div class="col-md-12">
        <div class="calm-welcome text-center">
            <%= image_tag('calm-welcome.png') %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 text-center">
       <%= form_for @comment, url: new_comment_url(@blog) do |form| %>
            <div class="form-group text-center">
                <p>
                    <%= form.label :body %><br>
                    <%= form.text_area :body %>
                </p>
                <p>
                    <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
                </p>
            </div>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body text-center">
                <h4>Your Story</h4>
            </div>
        </div>
        <div class="main-text-box">
            <p class="text-center"><%= @blog.text %></p>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <%= image_tag(@blog.image_url, class: 'img-responsive') %>
    </div>
</div>


<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h3 class="text-center">Comments</h3>
        <% @blog.comments.each do |comment| %>
            <% next if comment.new_record? %>
            <div>
                <small>On <%= comment.created_at.strftime("%d.%m.%Y") %></small> <strong><%= comment.commenter %></strong> wrote:<br>
                <%= comment.body %>
            </div>
        <% end %>
    </div>
</div>

app/views/frontend/subscriptions/new.html.erb
<%= form_for @subscription, :url => {:controller => "subscriptions", :action => "create"} do |form| %>

     <div class="form-group">
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :last_name %><br>
        <%= form.text_area :last_name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :email %><br>
        <%= form.text_area :email, class: 'form-control' %>
    </div>

    <p>
        <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...', confirm: 'Are you sure?' } %>
    </p>

<% end %>

app/views/layouts/_devise.html.erb
<% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, class: "btn btn-primary",  method: :delete) %>
<% else %>
    <%= link_to('Login', new_user_session_path, class: "btn btn-primary")  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogpost</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

    <body>
       <nav class="navbar navbar-default">
           <div class="container-fluid">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   </button>
                   <a class="navbar-brand" href="#">My Blog</a>
               </div>
               <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                   <ul class="nav navbar-nav">
                       <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
                       <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Backend<span class="caret"></span></a>
                         <ul class="dropdown-menu">
                           <li><%= link_to "Blogs", backend_blogs_path %></li>
                           <li><%= link_to "Comments", backend_comments_path %></li>
                           <li><%= link_to "Subscriptions", backend_blogs_path %></li>
                         </ul>
                       </li>
                   </ul>
               </div>
           </div>
       </nav>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <% if notice %>
                        <p class="alert alert-success"><%= notice %></p>
                    <% end %>
                    <% if alert %>
                        <p class="alert alert-danger"><%= alert %></p>
                    <% end %>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                <%= yield %>
                </div>
            </div>
        </div>
    </body>
</html>